spring:
    application:
        name: customers-microservice
server:
    port: 20031
security:
    oauth2:
        client: 
            clientId: acme
            clientSecret: acmesecret
        resource:
            tokenInfoUri: http://localhost:40051/oauth/check_token

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:17001/eureka/

---

spring:
    profiles: instance1
server:
    port: 20032

---

spring:
    profiles: instance2
server:
    port: 20033